source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem "minima", "~> 2.0"
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jemoji'
gem 'jekyll-readme-index'
